# Generated by Django 4.0.3 on 2022-12-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binvo',
            name='import_href',
            field=models.CharField(default='http://www.google.com', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
